l10n.addResource('en_us', {
    "Home": "Home",
    "Help": "Help",
    "User": "User",
    "Role": "Role",
    "Organization": "Organization",
    "Menu": "Menu",
    "Submenu": "Submenu",
    "Settings": "Settings",
    "Password": "Password",
    "Global Dictionary": "Global Dictionary",
    "Local Dictionary": "Local Dictionary",
    "Dictionary Type": "Dictionary Type",
    "System Management": "System Management",
    "System Configuration": "System Configuration",
    "User Settings": "User Settings",
    "Select Organization": "Select Organization",
    "Generic Platform": "Generic Platform",
    "Global": "Global",
    "Total": "Total",
    "Item(s)": "Item(s)",
    "Page(s)": "Page(s)",
    "Go": "Go",
    "About": "About",
    "Confirm": "Confirm",
    "Operation": "Operation",
    "Delete": "Delete",
    "Add": "Add",
    "Modify": "Modify",
    "Criteria": "Criteria",
    "Search": "Search",
    "Reset": "Reset",
    "Version": "Version",
    "Language": "Language",
    "None": "N/A",
    "Save": "Save",
    "Time": "Time",
    "Status": "Status",
    "Search": "Search",
    "Input Password": "Input Password",
    "Authentication Fail": "Authentication Fail",
    "Password Setting": "Password Setting",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "New Password Again": "New Password Again",
    "New password mismatch": "New password mismatch",
    "Password can't be empty": "Password can't be empty",
    "Password min length": "Password length must great then 6",
    "Save success": "Save success",
    "Apply": "Apply",
    "OK": "OK",
    "Cancel": "Cancel",
    "Can't delete current user": "Can't delete current user",
    "No Permission": "No Permission",
    "Built-in role can't be removed": "Built-in role can't be removed",
    "Built-in role can't be changed": "Built-in role can't be changed",
    "Please Select": "Please Select",
    "Logout": "Logout",
    "UserRole": "User's Role",
    "Success": "Success",
    "Error": "Error",
    "Server Side Error": "Server Side Error",
    "Warning": "Warning",
    "Attention": "Attention",
    "Unknown": "Unknown",
    "ms": "ms",
    "TimeZone": "Time Zone",
    "MessageCount": "Message Count",
    "Frequency": "Frequency",

    "UserCode": "User Code",
    "UserName": "User Name",
    "Enabled": "Enabled",
    "ResetPassword": "Reset Password",
    "Code": "Code",
    "Name": "Name",
    "Register": "Register",
    "Description": "Description",
    "Authorization": "Authorization",
    "Address": "Address",
    "Tel": "Tel",
    "Comment": "Comment",
    "Type": "Type",
    "Value": "Value",
    "Icon": "Icon",
    "Link": "Link",
    "DisplayOrder": "Display Order",
    "Localization": "Localization",
    "ParentMenu": "Parent Menu"
});