l10n.addResource('zh_cn', {
    "Home": "首页",
    "Help": "帮助",
    "User": "用户",
    "Role": "角色",
    "Organization": "机构",
    "Menu": "菜单",
    "Submenu": "子菜单",
    "Settings": "设置",
    "Password": "密码",
    "Global Dictionary": "全局字典",
    "Local Dictionary": "局部字典",
    "Dictionary Type": "字典类型",
    "System Management": "系统管理",
    "System Configuration": "系统配置",
    "User Settings": "用户设置",
    "Select Organization": "选择机构",
    "Generic Platform": "通用平台",
    "Global": "全局",
    "Total": "总共",
    "Item(s)": "项",
    "Page(s)": "页",
    "Go": "跳转",
    "About": "关于",
    "Confirm": "确认",
    "Operation": "操作",
    "Delete": "删除",
    "Add": "添加",
    "Modify": "修改",
    "Criteria": "条件",
    "Search": "查询",
    "Reset": "重置",
    "Version": "版本",
    "Language": "语言",
    "None": "无效",
    "Save": "保存",
    "Time": "时间",
    "Status": "状态",
    "Search": "查询",
    "Input Password": "输入密码",
    "Authentication Fail": "认证失败",
    "Password Setting": "密码设置",
    "Old Password": "旧密码",
    "New Password": "新密码",
    "New Password Again": "确认新密码",
    "New password mismatch": "新密码不一致",
    "Password can't be empty": "密码不能为空",
    "Password min length": "密码至少6位",
    "Save success": "保存成功",
    "Apply": "应用",
    "OK": "确认",
    "Cancel": "取消",
    "Can't delete current user": "不能删除当前用户",
    "No Permission": "没有权限",
    "Built-in role can't be removed": "内置角色不能删除",
    "Built-in role can't be changed": "内置角色不能修改",
    "Please Select": "请选择",
    "Logout": "注销",
    "UserRole": "用户角色",
    "System Status": "系统状态",
    "Success": "成功",
    "Error": "错误",
    "Server Side Error": "服务器错误",
    "Warning": "异常",
    "Attention": "注意",
    "Unknown": "未知",
    "ms": "毫秒",
    "TimeZone": "时区",
    "MessageCount": "消息数量",
    "Frequency": "频率",

    "UserCode": "用户名",
    "UserName": "姓名",
    "Enabled": "可用",
    "ResetPassword": "重置密码",
    "Code": "代码",
    "Name": "名称",
    "Register": "注册",
    "Description": "描述",
    "Authorization": "授权",
    "Address": "地址",
    "Tel": "电话",
    "Comment": "备注",
    "Type": "类型",
    "Value": "值",
    "Icon": "图标",
    "Link": "链接",
    "DisplayOrder": "显示顺序",
    "Localization": "本地化",
    "ParentMenu": "上级菜单"
});